name: Deploy Next.js App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Show .env contents (for debugging only - remove later)
        run: cat .env

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nextjs-app:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nextjs-app:latest

      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo "Pulling latest image..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/nextjs-app:latest

            echo "Removing any previous container..."
            docker rm -f nextjs-app || true

            echo "Killing any process using port 3000..."
            PID=$(sudo lsof -ti:3000)
            if [ ! -z "$PID" ]; then
              sudo kill -9 $PID
              echo "Killed process $PID using port 3000"
            else
              echo "No process was using port 3000"
            fi

            echo "Waiting 3 seconds..."
            sleep 3

            echo "Running Docker container..."
            docker run -d --name nextjs-app -p 3000:3000 \
              -e NODE_ENV=production \
              ${{ secrets.DOCKER_USERNAME }}/nextjs-app:latest

